export const PRONOUNCEABLE_SYLLABLES = [
  'ba', 'be', 'bi', 'bo', 'bu', 'by', 'ca', 'ce', 'ci', 'co', 'cu', 'cy',
  'da', 'de', 'di', 'do', 'du', 'dy', 'fa', 'fe', 'fi', 'fo', 'fu', 'fy',
  'ga', 'ge', 'gi', 'go', 'gu', 'gy', 'ha', 'he', 'hi', 'ho', 'hu', 'hy',
  'ka', 'ke', 'ki', 'ko', 'ku', 'ky', 'la', 'le', 'li', 'lo', 'lu', 'ly',
  'ma', 'me', 'mi', 'mo', 'mu', 'my', 'na', 'ne', 'ni', 'no', 'nu', 'ny',
  'pa', 'pe', 'pi', 'po', 'pu', 'py', 'ra', 're', 'ri', 'ro', 'ru', 'ry',
  'sa', 'se', 'si', 'so', 'su', 'sy', 'ta', 'te', 'ti', 'to', 'tu', 'ty',
  'va', 've', 'vi', 'vo', 'vu', 'vy', 'wa', 'we', 'wi', 'wo', 'wu', 'wy',
  'za', 'ze', 'zi', 'zo', 'zu', 'zy',
];

export const MEMORABLE_WORDS = [
  'Sun', 'Moon', 'Star', 'Sky', 'Sea', 'Tree', 'Cat', 'Dog', 'Bird', 'Fish',
  'Red', 'Blue', 'Gold', 'Pink', 'Green', 'White', 'Black', 'Gray', 'Big',
  'Small', 'Fast', 'Slow', 'Hot', 'Cold', 'New', 'Old', 'Good', 'Nice',
  'Cool', 'Warm', 'Safe', 'Happy', 'Lucky', 'Smart', 'Home', 'Work', 'Play',
  'Game', 'Book', 'Key', 'Door', 'Car', 'Love', 'Hope', 'Dream', 'Life',
  'Time', 'Day', 'Year', 'Way', 'Light', 'Dark', 'Rain', 'Storm', 'Cloud',
  'Snow', 'River', 'Mountain', 'Forest', 'Path', 'Road', 'Bridge', 'Garden',
  'Flower', 'Leaf', 'Stone', 'Rock', 'Sand', 'Beach', 'Wave', 'Shell', 'Boat',
  'Ship', 'Island', 'Castle', 'Tower', 'Knight', 'King', 'Queen', 'Prince',
  'Princess', 'Hero', 'Villain', 'Dragon', 'Wizard', 'Magic', 'Spell', 'Potion',
  'Sword', 'Shield', 'Arrow', 'Bow', 'Helmet', 'Armor', 'Battle', 'War',
  'Peace', 'Friend', 'Enemy', 'Ally', 'Stranger', 'Traveler', 'Explorer',
  'Hunter', 'Gatherer', 'Farmer', 'Builder', 'Maker', 'Creator', 'Inventor',
  'Artist', 'Singer', 'Dancer', 'Writer', 'Reader', 'Thinker', 'Dreamer',
  'Leader', 'Follower', 'Teacher', 'Student', 'Child', 'Parent', 'Family',
  'Friendship', 'Happiness', 'Joy', 'Sadness', 'Anger', 'Fear', 'Courage',
  'Bravery', 'Wisdom', 'Knowledge', 'Truth', 'Justice', 'Freedom', 'Honor',
  'Glory', 'Victory', 'Defeat', 'Challenge', 'Adventure', 'Journey', 'Quest',
  'Mission', 'Goal', 'Purpose', 'Destiny', 'Fate', 'Luck', 'Chance',
  'Opportunity', 'Choice', 'Decision', 'Action', 'Effort', 'Success', 'Failure',
  'Progress', 'Growth', 'Change', 'Moment', 'Memory', 'History', 'Future',
  'Past', 'Present', 'Reality', 'Fantasy', 'Imagination', 'Creativity',
  'Inspiration', 'Idea', 'Thought', 'Mind', 'Soul', 'Heart', 'Body', 'Spirit',
  'Energy', 'Power', 'Strength', 'Weakness', 'Speed', 'Agility', 'Skill',
  'Talent', 'Ability', 'Potential', 'Achievement', 'Accomplishment', 'Mastery',
  'Excellence', 'House', 'Music', 'Story', 'Water', 'Paper', 'Phone', 'Apple', 
  'Banana', 'Orange', 'Coffee', 'Pizza', 'Money', 'Planet', 'Robot', 'Guitar', 'Ocean', 
  'Summer', 'Winter', 'Spring', 'Autumn', 'Chocolate', 'Holiday', 'Mystery', 
  'Secret', 'Silence', 'Smile', 'Sunrise', 'Sunset', 'Thunder', 'Lightning', 
  'Universe', 'Treasure', 'Wonder', 'Abyss', 'Apex', 'Breeze', 'Cascade', 'Dawn', 
  'Echo', 'Flame', 'Galaxy', 'Haven', 'Infinity', 'Comet', 'Asteroid', 'Nebula', 'Quasar', 
  'Pulsar', 'Cosmos', 'Orbit', 'Axis', 'Gravity', 'Force', 'Matter', 'Atom', 'Molecule', 'Particle', 
  'Quantum', 'Theory', 'Logic', 'Reason', 'Intellect', 'Genius', 'Talent', 'Virtue', 'Vice', 'Sin', 'Grace', 
  'Mercy', 'Justice', 'Order', 'Chaos', 'Balance', 'Harmony', 'Melody', 'Rhythm', 'Symphony', 'Opera', 
  'Ballet', 'Theater', 'Cinema', 'Novel', 'Poem', 'Verse', 'Prose', 'Myth', 'Legend', 'Fable', 'Parable', 
  'Allegory', 'Metaphor', 'Simile', 'Irony', 'Satire', 'Humor', 'Tragedy', 'Comedy', 'Drama', 'Act', 
  'Scene', 'Chapter', 'Volume', 'Library', 'Archive', 'Museum', 'Gallery', 'Studio', 'Workshop', 'Laboratory', 
  'Observatory', 'Academy', 'University', 'College', 'School', 'Class', 'Degree', 'Diploma', 'Certificate', 
  'Medal', 'Trophy', 'Award', 'Prize', 'Fame', 'Legacy', 'Heritage', 'Tradition', 'Culture', 'Civilization', 
  'Nation', 'State', 'Empire', 'Kingdom', 'Republic', 'Democracy', 'Monarchy', 'Anarchy'
];

export const MEMORABLE_ADJECTIVES = [
  'Bright', 'Quick', 'Strong', 'Sweet', 'Gentle', 'Brave', 'Calm', 'Wild',
  'Soft', 'Sharp', 'Smooth', 'Fresh', 'Clean', 'Pure', 'Rich', 'Deep', 'Warm',
  'Cool', 'Hot', 'Cold', 'Fast', 'Slow', 'Big', 'Small', 'Tall', 'Short',
  'Wide', 'Narrow', 'Thick', 'Thin', 'Heavy', 'Light', 'Dark', 'Shiny', 'Dull',
  'Colorful', 'Pale', 'Vivid', 'Lively', 'Quiet', 'Noisy', 'Loud', 'Silent',
  'Peaceful', 'Angry', 'Happy', 'Sad', 'Joyful', 'Cheerful', 'Merry', 'Friendly',
  'Kind', 'Rough', 'Polite', 'Rude', 'Honest', 'Dishonest', 'Cowardly', 'Wise',
  'Foolish', 'Smart', 'Clever', 'Dumb', 'Stupid', 'Lazy', 'Hardworking',
  'Energetic', 'Tired', 'Hungry', 'Thirsty', 'Full', 'Empty', 'Open', 'Closed',
  'Safe', 'Dangerous', 'Secure', 'Insecure', 'Weak', 'Healthy', 'Sick', 'Poor',
  'Wealthy', 'Needy', 'Generous', 'Greedy', 'Selfish', 'Unselfish', 'Excited',
  'Bored', 'Interested', 'Uninterested', 'Curious', 'Uncurious', 'Bold', 'Timid',
  'Confident', 'Shy', 'Outgoing', 'Reserved', 'Talkative', 'Unfriendly', 'Mean',
  'Nice', 'Nasty', 'Sour', 'Bitter', 'Salty', 'Spicy', 'Stale', 'Dirty', 'Impure',
  'Violent', 'Ancient', 'Modern', 'Simple', 'Complex', 'Giant', 'Tiny', 
  'Humble', 'Proud', 'Innocent', 'Guilty', 'Loyal', 'Royal', 'Majestic', 'Mystic', 'Cosmic', 
  'Digital', 'Virtual', 'Quantum', 'Atomic', 'Golden', 'Silver', 'Bronze', 'Amber', 'Coral', 
  'Crimson', 'Emerald', 'Jade', 'Lemon', 'Magenta', 'Maroon', 'Navy', 'Olive', 'Orchid', 'Ruby', 
  'Sapphire', 'Scarlet', 'Teal', 'Turquoise', 'Violet', 'Awesome', 'Beautiful', 'Brilliant', 
  'Excellent', 'Fabulous', 'Fantastic', 'Glorious', 'Gorgeous', 'Incredible', 'Absolute', 'Abstract', 
  'Absurd', 'Actual', 'Acute', 'Adamant', 'Adept', 'Aerate', 'Agile', 'Alert', 'Alien', 'Alike', 'Alive', 'Aloof', 
  'Amazing', 'Ample', 'Antique', 'Apparent', 'Apt', 'Arbitrary', 'Arid', 'Artful', 'Astute', 'Attentive', 
  'Authentic', 'Avid', 'Awful', 'Awkward', 'Azure', 'Barren', 'Basic', 'Beneficial', 'Benign', 'Bizarre', 
  'Bland', 'Blank', 'Bleak', 'Blind', 'Blissful', 'Bouncy', 'Boundless', 'Brash', 'Brief', 'Brisk', 
  'Broad', 'Broken', 'Brotherly', 'Brown', 'Bubbly', 'Bulky', 'Bumpy', 'Buoyant', 'Burly', 'Busy', 'Cagey', 
  'Calculating', 'Callous', 'Candid', 'Canine', 'Capable', 'Capital', 'Carefree', 'Careful', 'Careless', 
  'Caring', 'Casual', 'Cautious', 'Ceaseless', 'Celestial', 'Certain', 'Changeable', 'Charming', 'Cheap', 
  'Cheery', 'Chief', 'Chilly', 'Chubby', 'Circular', 'Classic', 'Clear', 'Close', 'Cloudy', 'Clueless', 
  'Clumsy', 'Cluttered', 'Coarse', 'Coherent', 'Colossal', 'Combative', 'Comfortable', 'Common', 'Complete', 'Composed', 
  'Concerned', 'Concise', 'Concrete'
];

export const PASSPHRASE_WORDS = [
  'Blue', 'Green', 'Red', 'Yellow', 'Orange', 'Purple', 'Pink', 'Black',
  'White', 'Gray', 'Silver', 'Gold', 'Bronze',
  'Sky', 'Sea', 'Rain', 'Snow', 'Wind', 'Storm', 'Cloud', 'Sun', 'Moon',
  'Star', 'Light', 'Dark', 'Fire', 'Water', 'Earth', 'Air',
  'Apple', 'Orange', 'Banana', 'Cherry', 'Grape', 'Lemon', 'Mango',
  'Rose', 'Lily', 'Tulip', 'Daisy', 'Sunflower', 'Orchid',
  'Mountain', 'Valley', 'River', 'Lake', 'Ocean', 'Beach', 'Forest',
  'Tree', 'Flower', 'Plant', 'Grass', 'Leaf',
  'Dog', 'Cat', 'Bird', 'Fish', 'Lion', 'Tiger', 'Eagle', 'Dolphin',
  'Swift', 'Quick', 'Fast', 'Slow', 'Strong', 'Gentle', 'Brave', 'Wise',
  'Happy', 'Bright', 'Clear', 'Fresh', 'Clean', 'Smooth', 'Sharp',
  'Journey', 'Adventure', 'Quest', 'Mission', 'Victory', 'Success',
  'Dream', 'Hope', 'Peace', 'Harmony', 'Balance', 'Energy', 'Power',
  'Castle', 'Palace', 'Tower', 'Bridge', 'Garden', 'Temple',
  'Knight', 'King', 'Queen', 'Prince', 'Princess', 'Hero', 'Legend', 'Amber', 'Blaze', 
  'Bloom', 'Bolt', 'Chill', 'Crest', 'Crimson', 'Crown', 'Crystal', 'Delta', 'Dew', 
  'Echo', 'Ember', 'Emerald', 'Enigma', 'Fjord', 'Flame', 'Flash', 'Flux', 'Frost', 'Garnet', 
  'Glacier', 'Glimmer', 'Glow', 'Grove', 'Halo', 'Haze', 'Helix', 'Horizon', 'Infinity', 'Ivory', 
  'Jade', 'Jolt', 'Lagoon', 'Lava', 'Labyrinth', 'Mirage', 'Mist', 'Myth', 'Nebula', 
  'Nexus', 'Oasis', 'Obsidian', 'Onyx', 'Oracle', 'Orbit', 'Pulse', 'Pyramid', 'Aegis', 
  'Aether', 'Altar', 'Apex', 'Aqua', 'Arcane', 'Aria', 'Arrow', 'Ash', 'Atlas', 'Aura', 'Aurora', 
  'Avalanche', 'Axiom', 'Axis', 'Azure', 'Beacon', 'Bell', 'Blade', 'Bliss', 'Blizzard', 'Canyon', 
  'Cape', 'Cavern', 'Celestial', 'Chalice', 'Chasm', 'Chronicle', 'Cipher', 'Claw', 'Cliff', 'Cloak', 
  'Comet', 'Core', 'Cove', 'Crater', 'Creed', 'Cyclone', 'Dawn', 'Dire', 'Divine', 'Domain', 'Drake', 
  'Dune', 'Dust', 'Eclipse', 'Edict', 'Eon', 'Epoch', 'Essence', 'Eventide', 'Fable', 'Fang', 'Fauna', 
  'Fell', 'Fen', 'Fern', 'Abyss', 'Amulet', 'Anchor', 'Angel', 'Anomaly', 'Antique', 'Anvil', 'Apogee', 
  'Apostle', 'Arc', 'Arch', 'Archive', 'Arctic', 'Argent', 'Ark', 'Armor', 'Artifact', 'Artisan', 'Ashes', 
  'Asylum', 'Atoll', 'Augur', 'Autumn', 'Avatar', 'Avenue', 'Bauble', 'Beam', 'Beast', 'Bible', 
  'Blessing', 'Bohemian', 'Bonsai', 'Boon', 'Boulder', 'Boulevard', 'Boundary', 'Bouquet'
];

export const SOCIAL_PASSWORD_SYLLABLES = [
  'ba', 'be', 'bi', 'bo', 'bu', 'ca', 'ce', 'ci', 'co', 'cu', 'da', 'de',
  'di', 'do', 'du', 'fa', 'fe', 'fi', 'fo', 'fu', 'ga', 'ge', 'gi', 'go',
  'gu', 'ha', 'he', 'hi', 'ho', 'hu', 'ka', 'ke', 'ki', 'ko', 'ku', 'la',
  'le', 'li', 'lo', 'lu', 'ma', 'me', 'mi', 'mo', 'mu', 'na', 'ne', 'ni',
  'no', 'nu', 'pa', 'pe', 'pi', 'po', 'pu', 'ra', 're', 'ri', 'ro', 'ru',
  'sa', 'se', 'si', 'so', 'su', 'ta', 'te', 'ti', 'to', 'tu', 'wa', 'we',
  'wi', 'wo', 'wu', 'za', 'ze', 'zi', 'zo', 'zu',
];
