name: iOS Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: ios

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle exec pod install

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace PasswordEpic.xcworkspace \
            -scheme PasswordEpic \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            build

      - name: Archive iOS App (Release)
        if: github.ref == 'refs/heads/main'
        run: |
          cd ios
          xcodebuild -workspace PasswordEpic.xcworkspace \
            -scheme PasswordEpic \
            -configuration Release \
            -archivePath build/PasswordEpicRN.xcarchive \
            archive

      - name: Export IPA
        if: github.ref == 'refs/heads/main'
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/PasswordEpicRN.xcarchive \
            -exportPath build \
            -exportOptionsPlist exportOptions.plist

      - name: Upload IPA artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/build/*.ipa
          retention-days: 90
